### ISSUE TITLE
[Tutoriel - LUA]Modificateur de Rates d'EXP'

### ISSUE THREAD

**Issue by ghost** [Open-Wow/forum#35]
# Modificateur de Rates EXP'
### Partage par @iThorgrim-Hub 

Salut !
Alors comme j'avais envie de reprendre mon format tutoriel vidéo, je me suis dit que reprendre avec une tutoriel LUA pourrais être pas mal.

C'est donc fait et durant ce tutoriel vidéo je vous apprend à créer un Modificateur de Rates d'EXP'.

**Attention tout de même, je vous apprends rien sur le LUA en tant que tel, pour cela merci de faire quelques recherche Google, le LUA reste un langage très simple à prendre en main.**

*Cliquez sur l'image pour voir la vidéo*
[![La vidéo en question](https://i.ytimg.com/vi/9v_7s9Z5krA/maxresdefault.jpg)](https://www.youtube.com/watch?v=9v_7s9Z5krA)

**Comment by lyo3d** [comment]
the video is still available

**Comment by ghost** [comment]
@lyo3d Tutorial is here now -> https://forum.open-wow.eu/d/101-modificateur-de-rate-dexp
